### ISSUE TITLE
Crashes every activation on 7/Nougat

### ISSUE THREAD

**Issue by TPS** [balazsbanyai/auto-batterysaver-lollipop#1]
@balazsbanyai Please advise:  I've sent many crash reports via Google Services.  Now that I've tracked down this repo, how shall I proceed?

**Comment by balazsbanyai** [comment]
Thanks for bringing this to my attention! I'll look into it, and get back to you as soon as I determined the cause, and have a viable ETA.

Thank you very much!

**Comment by TPS** [comment]
Thank _you_ for being willing to investigate!

1 more note: until you get your own website setup, could you link _this_ repo from GPlay?  I found it accidentally, after _months_ of frustration.

**Comment by TPS** [comment]
If you want to make some sort of beta (maybe via https://play.google.com/apps/testing/com.banyaibalazs.batterysaverlollipop), I'm game to test. :smile:

**Comment by balazsbanyai** [comment]
Hey, 

I've released a beta version, that should aid this issue. Please report back you find it useful. I tested it on 6.0, and 7.0 devices, and found it to be working as expected.

Opt-in url for beta testing: https://play.google.com/apps/testing/com.banyaibalazs.batterysaverlollipop

Thank again!

**Comment by TPS** [comment]
Yep, looks like https://github.com/balazsbanyai/auto-batterysaver-lollipop/commit/20ffe22fb2f0408dd707213fdfdb1daad25eebce & https://github.com/balazsbanyai/auto-batterysaver-lollipop/commit/bb5d10ff3ba89e7401afbb2d5c2786346b5b664f fixed it!
Thanks so much!
